package vn.com.uit.ui.form;

import dtos.ClassDto;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import vn.com.uit.common.Constants;
import vn.uit.com.business.service.ClassService;
import vn.uit.com.contracts.service.IClassService;
import vn.uit.com.contracts.ui.IClassForm;

/**
 *
 * @author Admin
 */
public class ClassForm extends javax.swing.JPanel implements IClassForm {

    private IClassService _service;
    private DefaultTableModel _dm;

    /**
     * Creates new form ClassForm
     */
    public ClassForm() {
        initComponents();
        initialization();
        onLoading();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbClass = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(968, 438));

        txtSearch.setToolTipText("");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel1.setText("Tìm kiếm");

        btnNew.setBackground(new java.awt.Color(51, 51, 255));
        btnNew.setForeground(new java.awt.Color(0, 0, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/School_20px.png"))); // NOI18N
        btnNew.setText("Thêm");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew))
                .addContainerGap())
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 800));

        tbClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã lớp", "Tên lớp", "Mã khoá học", "Mã giảng viên", "Sỉ số", "Ngày bắt đầu", "Ngày kết thúc", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbClass.setFillsViewportHeight(true);
        tbClass.setGridColor(new java.awt.Color(204, 204, 255));
        tbClass.setInheritsPopupMenu(true);
        tbClass.setMaximumSize(new java.awt.Dimension(32767, 32767));
        tbClass.setMinimumSize(new java.awt.Dimension(23, 23));
        tbClass.setPreferredSize(new java.awt.Dimension(1000, 800));
        tbClass.setRowHeight(25);
        tbClass.setSelectionBackground(new java.awt.Color(51, 153, 255));
        tbClass.getTableHeader().setResizingAllowed(false);
        tbClass.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbClass);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String query = txtSearch.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        JFrame main = (JFrame) SwingUtilities.getWindowAncestor(this);

        NewClassForm dialog = new NewClassForm(main, true);
        int result = dialog.showDialog();

        if (result == Constants.STATUS_OK) {
            //reload
            _service.loadListClass();
        }
    }//GEN-LAST:event_btnNewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbClass;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void displayListClass(ArrayList<ClassDto> list) {
        if (_dm.getRowCount() != 0) {
            _dm.getDataVector().removeAllElements();
            _dm.fireTableDataChanged();
        }
        Object rowData[] = new Object[8];
        for (int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i).getId();
            rowData[1] = list.get(i).getName();
            rowData[2] = list.get(i).getCourseId();
            rowData[3] = list.get(i).getTeacherId();
            rowData[4] = list.get(i).getCurrentQuantity() + "/" + list.get(i).getCapacity();
            rowData[5] = list.get(i).getStartedDate();
            rowData[6] = list.get(i).getEndedDate();
            rowData[7] = list.get(i).isStatus() ? Constants.AVAILABLE : Constants.CLOSED;

            _dm.addRow(rowData);

        }
    }

    @Override
    public void initialization() {
        _service = new ClassService(this);
        _dm = (DefaultTableModel) tbClass.getModel();
    }

    @Override
    public void onLoading() {
        _service.loadListClass();

        tbClass.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                int r = tbClass.rowAtPoint(e.getPoint());
                if (r >= 0 && r < tbClass.getRowCount()) {
                    tbClass.setRowSelectionInterval(r, r);
                } else {
                    tbClass.clearSelection();
                }

                int rowindex = tbClass.getSelectedRow();
                if (rowindex < 0) {
                    return;
                }
                if (e.isPopupTrigger() && e.getComponent() instanceof JTable) {
                    JPopupMenu popup = createPopUp();
                    popup.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
    }

    private void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(_dm);
        tbClass.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter("(?i)" + query, 1, 2, 3, 4, 5));
    }

    private JPopupMenu createPopUp() {
        JPopupMenu result = new JPopupMenu();
        JMenuItem edit = new JMenuItem("Xem danh sách lớp");

        edit.addActionListener((ActionEvent e) -> {
            showDetailDialog();
        });

        result.add(edit);

        return result;
    }

    private void showDetailDialog() {
        TableModel model = tbClass.getModel();
        int index = tbClass.getSelectedRow();

        int classId = (int) model.getValueAt(index, 0);
        int courseId = (int) model.getValueAt(index, 2);

        JFrame main = (JFrame) SwingUtilities.getWindowAncestor(this);

        ListClassForm dialog = new ListClassForm(main, true, classId, courseId);
        int result = dialog.showDialog();
        if (result == Constants.STATUS_OK) {
            _service.loadListClass();
        }
    }

}
