package vn.com.uit.ui.form;

import dtos.CourseDto;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import vn.com.uit.common.Constants;
import vn.uit.com.business.service.CourseService;
import vn.uit.com.contracts.service.ICourseService;
import vn.uit.com.contracts.ui.ICourseForm;

/**
 *
 * @author Admin
 */
public class CourseForm extends javax.swing.JPanel implements ICourseForm {

    private ICourseService _service;
    private DefaultTableModel _dm;

    /**
     * Creates new form CourseForm
     */
    public CourseForm() {
        initComponents();
        initialization();
        onLoading();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCourse = new javax.swing.JTable();

        txtSearch.setToolTipText("");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel1.setText("Tìm kiếm");

        btnNew.setBackground(new java.awt.Color(51, 51, 255));
        btnNew.setForeground(new java.awt.Color(0, 0, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Classroom_20px.png"))); // NOI18N
        btnNew.setText("Thêm");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 463, Short.MAX_VALUE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew))
                .addContainerGap())
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 800));

        tbCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khoá học", "Tên khoá học", "Học phí", "Thời gian kéo dài (tuần)", "Điểm đầu vào", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCourse.setFillsViewportHeight(true);
        tbCourse.setGridColor(new java.awt.Color(204, 204, 255));
        tbCourse.setInheritsPopupMenu(true);
        tbCourse.setMaximumSize(new java.awt.Dimension(32767, 32767));
        tbCourse.setMinimumSize(new java.awt.Dimension(23, 23));
        tbCourse.setPreferredSize(new java.awt.Dimension(1000, 800));
        tbCourse.setRowHeight(25);
        tbCourse.setSelectionBackground(new java.awt.Color(51, 153, 255));
        tbCourse.getTableHeader().setResizingAllowed(false);
        tbCourse.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbCourse);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String query = txtSearch.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        JFrame main = (JFrame) SwingUtilities.getWindowAncestor(this);

        NewCourseForm dialog = new NewCourseForm(main, true);
        int result = dialog.showDialog();

        if (result == Constants.STATUS_OK) {
            //reload
            _service.loadListCourse();
        }
    }//GEN-LAST:event_btnNewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCourse;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void displayListCourse(ArrayList<CourseDto> list) {
        if (_dm.getRowCount() != 0) {
            _dm.getDataVector().removeAllElements();
            _dm.fireTableDataChanged();
        }
        Object rowData[] = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i).getId();
            rowData[1] = list.get(i).getName();
            rowData[2] = list.get(i).getFee().intValueExact();
            rowData[3] = list.get(i).getDuration();
            rowData[4] = list.get(i).getBenchmark();
            rowData[5] = list.get(i).isStatus() ? Constants.AVAILABLE : Constants.CLOSED;

            _dm.addRow(rowData);

        }
    }

    @Override
    public void initialization() {
        _service = new CourseService(this);
        _dm = (DefaultTableModel) tbCourse.getModel();
    }

    @Override
    public void onLoading() {
        _service.loadListCourse();

        tbCourse.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                int r = tbCourse.rowAtPoint(e.getPoint());
                if (r >= 0 && r < tbCourse.getRowCount()) {
                    tbCourse.setRowSelectionInterval(r, r);
                } else {
                    tbCourse.clearSelection();
                }

                int rowindex = tbCourse.getSelectedRow();
                if (rowindex < 0) {
                    return;
                }
                if (e.isPopupTrigger() && e.getComponent() instanceof JTable) {
                    JPopupMenu popup = createPopUp();
                    popup.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
    }

    private JPopupMenu createPopUp() {
        JPopupMenu result = new JPopupMenu();
        JMenuItem edit = new JMenuItem("Sửa");
        JMenuItem close = new JMenuItem("Đóng khoá học");

        edit.addActionListener((ActionEvent e) -> {
            showDetailDialog();
        });

        close.addActionListener((ActionEvent e) -> {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Đóng khoá học này?", "Nhắc nhở", JOptionPane.YES_NO_OPTION);
            if (dialogResult == JOptionPane.YES_OPTION) {
                int index = tbCourse.getSelectedRow();
                TableModel model = tbCourse.getModel();
                int courseId = (int) model.getValueAt(index, 0);
                _service.closeCourse(courseId);
                _service.loadListCourse();
            }
        });

        result.add(edit);
        result.add(close);

        return result;
    }

    private void showDetailDialog() {
        int index = tbCourse.getSelectedRow();
        TableModel model = tbCourse.getModel();

        CourseDto course = new CourseDto();
        course.setId((int) model.getValueAt(index, 0));
        course.setName((String) model.getValueAt(index, 1));
        course.setFee(BigDecimal.valueOf((new Integer((int) model.getValueAt(index, 2))).longValue()));
        course.setDuration((int) model.getValueAt(index, 3));
        course.setBenchmark((float) model.getValueAt(index, 4));
        boolean status = model.getValueAt(index, 5).equals(Constants.AVAILABLE);
        course.setStatus(status);

        JFrame main = (JFrame) SwingUtilities.getWindowAncestor(this);

        EditCourseForm dialog = new EditCourseForm(main, true, course);
        int result = dialog.showDialog();

        if (result == Constants.STATUS_OK) {
            //reload
            _service.loadListCourse();
        }

    }

    private void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(_dm);
        tbCourse.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter("(?i)" + query));
    }
}
