package vn.com.uit.ui.form;

import dtos.ClassDto;
import dtos.CourseDto;
import dtos.ParticipationDto;
import dtos.TraineeDto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import vn.com.uit.common.Constants;
import vn.uit.com.business.service.DistributionService;
import vn.uit.com.contracts.service.IDistributionService;
import vn.uit.com.contracts.ui.IDistributionForm;

/**
 *
 * @author Admin
 */
public class DistributionForm extends javax.swing.JPanel implements IDistributionForm {

    private IDistributionService _service;

    // variables for submit
    private int _traineeId = -1;
    private int _courseId = -1;
    private BigDecimal _fee;
    private int _staffId = -1;

    /**
     * Creates new form DistributionForm
     */
    public DistributionForm(int staffId) {
        initComponents();
        initialization();
        onLoading();
        this._staffId = staffId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSearchTrainee = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        btnSearchTrainee = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbTraineeName = new javax.swing.JLabel();
        lbTraineeBirthday = new javax.swing.JLabel();
        lbTraineeAddress = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbTraineeMark = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCourseTaken = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtSearchClass = new javax.swing.JTextField();
        btnSearchClass = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbCourseName = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbClass = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 392));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 392));

        txtSearchTrainee.setToolTipText("");

        btnNew.setBackground(new java.awt.Color(51, 51, 255));
        btnNew.setForeground(new java.awt.Color(0, 0, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Add User Male_20px.png"))); // NOI18N
        btnNew.setText("Thêm");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSearchTrainee.setText("Tìm kiếm");
        btnSearchTrainee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTraineeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchTrainee, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchTrainee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchTrainee, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew)
                    .addComponent(btnSearchTrainee))
                .addContainerGap())
        );

        jLabel1.setLabelFor(lbTraineeName);
        jLabel1.setText("Họ và tên:");

        jLabel2.setLabelFor(lbTraineeBirthday);
        jLabel2.setText("Ngày sinh:");

        jLabel3.setLabelFor(lbTraineeAddress);
        jLabel3.setText("Địa chỉ:");

        lbTraineeName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTraineeName.setForeground(new java.awt.Color(0, 0, 204));

        lbTraineeBirthday.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTraineeBirthday.setForeground(new java.awt.Color(0, 0, 204));

        lbTraineeAddress.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTraineeAddress.setForeground(new java.awt.Color(0, 0, 204));

        jLabel5.setLabelFor(lbTraineeMark);
        jLabel5.setText("Điểm đầu vào:");

        lbTraineeMark.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbTraineeMark.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTraineeName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTraineeBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTraineeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTraineeMark, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbTraineeMark, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lbTraineeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(lbTraineeName, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbTraineeBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbCourseTaken.setBackground(new java.awt.Color(204, 204, 255));
        tbCourseTaken.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khoá học", "Tên khoá học", "Mã lớp", "Tên lớp", "Điểm hoàn thành"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbCourseTaken.setFillsViewportHeight(true);
        tbCourseTaken.setRowHeight(25);
        jScrollPane1.setViewportView(tbCourseTaken);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtSearchClass.setToolTipText("");

        btnSearchClass.setText("Tìm kiếm");
        btnSearchClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchClassActionPerformed(evt);
            }
        });

        jLabel4.setLabelFor(lbCourseName);
        jLabel4.setText("Khoá học:");

        lbCourseName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCourseName.setForeground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchClass, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchClass)
                .addGap(207, 207, 207)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchClass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchClass)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbClass.setBackground(new java.awt.Color(204, 204, 255));
        tbClass.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã lớp", "Tên lớp", "Sỉ số", "Thời gian học", "Ngày bắt đầu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbClass.setFillsViewportHeight(true);
        tbClass.setRowHeight(25);
        jScrollPane2.setViewportView(tbClass);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        JFrame main = (JFrame) SwingUtilities.getWindowAncestor(this);

        NewTraineeForm dialog = new NewTraineeForm(main, true);
        int result = dialog.showDialog();

        if (result == Constants.STATUS_OK) {
            //reload
            _service.searchTrainee(0, Constants.FLAG_DEFAULT);
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSearchTraineeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTraineeActionPerformed
        try {
            int traineeId = Integer.parseInt(txtSearchTrainee.getText());
            _service.searchTrainee(traineeId, Constants.FLAG_SEARCH);
        } catch (NumberFormatException e) {
            // Wrong id format! Do nothing.
        }
    }//GEN-LAST:event_btnSearchTraineeActionPerformed

    private void btnSearchClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchClassActionPerformed
        try {
            int courseId = Integer.parseInt(txtSearchClass.getText());
            _service.searchClass(courseId);
        } catch (NumberFormatException ex) {
            // Wrong id format! Do nothing.
        }
    }//GEN-LAST:event_btnSearchClassActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSearchClass;
    private javax.swing.JButton btnSearchTrainee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCourseName;
    private javax.swing.JLabel lbTraineeAddress;
    private javax.swing.JLabel lbTraineeBirthday;
    private javax.swing.JLabel lbTraineeMark;
    private javax.swing.JLabel lbTraineeName;
    private javax.swing.JTable tbClass;
    private javax.swing.JTable tbCourseTaken;
    private javax.swing.JTextField txtSearchClass;
    private javax.swing.JTextField txtSearchTrainee;
    // End of variables declaration//GEN-END:variables

    @Override
    public void displayTraineeInfo(TraineeDto trainee, ArrayList<ParticipationDto> listParticipations) {

        _traineeId = trainee.getId();

        refreshTraineePanel();

        lbTraineeName.setText(trainee.getName());
        lbTraineeAddress.setText(trainee.getAddress());
        lbTraineeBirthday.setText(trainee.getBirthday().toString());
        lbTraineeMark.setText(String.valueOf(trainee.getTestMark()));

        DefaultTableModel _dm = (DefaultTableModel) tbCourseTaken.getModel();

        if (listParticipations == null) {
            return;
        }

        Object rowData[] = new Object[8];
        for (int i = 0; i < listParticipations.size(); i++) {
            rowData[0] = listParticipations.get(i).getCourseId();
            rowData[1] = listParticipations.get(i).getCourseName();
            rowData[2] = listParticipations.get(i).getClassId();
            rowData[3] = listParticipations.get(i).getClassName();
            rowData[4] = listParticipations.get(i).getMark();

            _dm.addRow(rowData);
        }
    }

    @Override
    public void displayListClassInCourse(CourseDto course, ArrayList<ClassDto> list) {

        _courseId = course.getId();
        _fee = course.getFee();

        refreshClassPanel();

        lbCourseName.setText(course.getName());

        DefaultTableModel _dm = (DefaultTableModel) tbClass.getModel();

        Object rowData[] = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i).getId();
            rowData[1] = list.get(i).getName();
            rowData[2] = list.get(i).getCurrentQuantity() + "/" + list.get(i).getCapacity();
            rowData[3] = list.get(i).getTime();
            rowData[4] = list.get(i).getStartedDate();

            _dm.addRow(rowData);
        }
    }

    @Override
    public void displayMessage(String msg, int flag) {
        JOptionPane.showMessageDialog(null, msg, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        if (flag == Constants.FLAG_REFRESH) {
            int index = tbClass.getSelectedRow();
            TableModel model = tbClass.getModel();
            int classId = (int) model.getValueAt(index, 0);
            _service.printReceipt(_courseId, classId, _traineeId, _staffId);
            refreshUI();
        }
    }

    @Override
    public void initialization() {
        _service = new DistributionService(this);
    }

    @Override
    public void onLoading() {

        tbClass.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                int r = tbClass.rowAtPoint(e.getPoint());
                if (r >= 0 && r < tbClass.getRowCount()) {
                    tbClass.setRowSelectionInterval(r, r);
                } else {
                    tbClass.clearSelection();
                }

                int rowindex = tbClass.getSelectedRow();
                if (rowindex < 0) {
                    return;
                }
                if (e.isPopupTrigger() && e.getComponent() instanceof JTable) {
                    JPopupMenu popup = createPopUp();
                    popup.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
    }

    private JPopupMenu createPopUp() {
        JPopupMenu result = new JPopupMenu();
        JMenuItem register = new JMenuItem("Thêm vào lớp");

        register.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (_traineeId != -1 && _courseId != -1) {
                    showConfirmDialog();
                } else {
                    JOptionPane.showMessageDialog(null, "Chưa chọn học viên", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        result.add(register);

        return result;
    }

    private void showConfirmDialog() {
        int index = tbClass.getSelectedRow();
        TableModel model = tbClass.getModel();
        int classId = (int) model.getValueAt(index, 0);

        String msg = "Ghi danh học viên [ " + _traineeId + " ] vào lớp [ " + classId + " ] thuộc khoá học [ " + _courseId + " ] ? \n"
                + "Học phí thu tiền mặt: [ " + _fee.intValueExact() + " vnd ]";
        int dialogResult = JOptionPane.showConfirmDialog(this, msg, "Thông báo xác nhận", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (dialogResult == JOptionPane.YES_OPTION) {
            _service.enrollClass(_courseId, classId, _traineeId);
        }
    }

    private void refreshTraineePanel() {
        lbTraineeName.setText("");
        lbTraineeAddress.setText("");
        lbTraineeBirthday.setText("");
        lbTraineeMark.setText("");

        DefaultTableModel _dm = (DefaultTableModel) tbCourseTaken.getModel();
        if (_dm.getRowCount() != 0) {
            _dm.getDataVector().removeAllElements();
            _dm.fireTableDataChanged();
        }
    }

    private void refreshClassPanel() {
        lbCourseName.setText("");

        DefaultTableModel _dm = (DefaultTableModel) tbClass.getModel();
        if (_dm.getRowCount() != 0) {
            _dm.getDataVector().removeAllElements();
            _dm.fireTableDataChanged();
        }
    }

    private void refreshUI() {
        refreshTraineePanel();
        refreshClassPanel();
        txtSearchClass.setText("");
        txtSearchTrainee.setText("");
        _traineeId = -1;
        _courseId = -1;
        _fee = null;
    }
}
