package vn.com.uit.ui.form;

import dtos.StaffDto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import vn.com.uit.common.Constants;
import vn.uit.com.business.service.StaffService;
import vn.uit.com.contracts.service.IStaffService;
import vn.uit.com.contracts.ui.IStaffForm;

/**
 *
 * @author Admin
 */
public class StaffForm extends javax.swing.JPanel implements IStaffForm {

    private IStaffService _service;
    private DefaultTableModel _dm;

    /**
     * Creates new form StaffForm
     */
    public StaffForm() {
        initComponents();
        initialization();
        onLoading();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStaff = new javax.swing.JTable();

        txtSearch.setToolTipText("");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel1.setText("Tìm kiếm");

        btnNew.setBackground(new java.awt.Color(51, 51, 255));
        btnNew.setForeground(new java.awt.Color(0, 0, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Add User Male_20px.png"))); // NOI18N
        btnNew.setText("Thêm");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNew))
                .addContainerGap())
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 800));

        tbStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ và tên", "Số CMND", "Số điện thoại", "Lương", "Ngày vào làm", "Chức vụ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbStaff.setFillsViewportHeight(true);
        tbStaff.setGridColor(new java.awt.Color(204, 204, 255));
        tbStaff.setInheritsPopupMenu(true);
        tbStaff.setMaximumSize(new java.awt.Dimension(32767, 32767));
        tbStaff.setMinimumSize(new java.awt.Dimension(23, 23));
        tbStaff.setPreferredSize(new java.awt.Dimension(1000, 800));
        tbStaff.setRowHeight(25);
        tbStaff.setSelectionBackground(new java.awt.Color(51, 153, 255));
        tbStaff.getTableHeader().setResizingAllowed(false);
        tbStaff.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbStaff);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private JPopupMenu createPopUp() {
        JPopupMenu result = new JPopupMenu();
        JMenuItem edit = new JMenuItem("Sửa");
        JMenuItem delete = new JMenuItem("Xoá");

        edit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showDetailDialog();
            }
        });

        delete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int dialogResult = JOptionPane.showConfirmDialog(null, "Xoá nhân viên?", "Nhắc nhở", JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    int index = tbStaff.getSelectedRow();
                    TableModel model = tbStaff.getModel();
                    int staffId = (int) model.getValueAt(index, 0);
                    _service.deleteStaff(staffId);
                }
            }

        });

        result.add(edit);
        result.add(delete);

        return result;
    }

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String query = txtSearch.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        JFrame main = (JFrame) SwingUtilities.getWindowAncestor(this);

        NewStaffForm dialog = new NewStaffForm(main, true);
        int result = dialog.showDialog();

        if (result == Constants.STATUS_OK) {
            //reload
            _service.loadListStaff();
        }
    }//GEN-LAST:event_btnNewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbStaff;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    @Override
    public void displayListStaff(ArrayList<StaffDto> list) {
        if (_dm.getRowCount() != 0) {
            _dm.getDataVector().removeAllElements();
            _dm.fireTableDataChanged();
        }
        Object rowData[] = new Object[7];
        for (int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i).getId();
            rowData[1] = list.get(i).getName();
            rowData[2] = list.get(i).getIdentityCardNumber();
            rowData[3] = list.get(i).getPhoneNum();
            rowData[4] = list.get(i).getSalary().intValueExact();
            rowData[5] = list.get(i).getStartedDate();
            rowData[6] = list.get(i).getRole();

            _dm.addRow(rowData);

        }
    }

    @Override
    public void displayErrorMsg(String msg) {
        JOptionPane.showMessageDialog(null, msg, "Lỗi", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void initialization() {
        _dm = (DefaultTableModel) tbStaff.getModel();
        _service = new StaffService(this);
    }

    @Override
    public void onLoading() {
        _service.loadListStaff();

        tbStaff.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                int r = tbStaff.rowAtPoint(e.getPoint());
                if (r >= 0 && r < tbStaff.getRowCount()) {
                    tbStaff.setRowSelectionInterval(r, r);
                } else {
                    tbStaff.clearSelection();
                }

                int rowindex = tbStaff.getSelectedRow();
                if (rowindex < 0) {
                    return;
                }
                if (e.isPopupTrigger() && e.getComponent() instanceof JTable) {
                    JPopupMenu popup = createPopUp();
                    popup.show(e.getComponent(), e.getX(), e.getY());
                }
            }
        });
    }

    private void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(_dm);
        tbStaff.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter("(?i)" + query));
    }

    private void showDetailDialog() {
        int index = tbStaff.getSelectedRow();
        TableModel model = tbStaff.getModel();

        StaffDto staff = new StaffDto();
        staff.setId((int) model.getValueAt(index, 0));
        staff.setName((String) model.getValueAt(index, 1));
        staff.setIdentityCardNumber((String) model.getValueAt(index, 2));
        staff.setPhoneNum((String) model.getValueAt(index, 3));
        staff.setSalary(BigDecimal.valueOf((new Integer((int) model.getValueAt(index, 4))).longValue()));
        staff.setStartedDate((Date) model.getValueAt(index, 5));
        staff.setRole((String) model.getValueAt(index, 6));

        JFrame main = (JFrame) SwingUtilities.getWindowAncestor(this);

        EditStaffForm dialog = new EditStaffForm(main, true, staff);
        int result = dialog.showDialog();

        if (result == Constants.STATUS_OK) {
            //reload
            _service.loadListStaff();
        }

    }
}
